# Generated by Django 5.2.6 on 2025-09-23 17:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(choices=[('+91', 'India (+91)'), ('+1', 'USA (+1)'), ('+44', 'UK (+44)'), ('+86', 'China (+86)'), ('+81', 'Japan (+81)'), ('+49', 'Germany (+49)'), ('+33', 'France (+33)'), ('+39', 'Italy (+39)'), ('+7', 'Russia (+7)'), ('+61', 'Australia (+61)'), ('+55', 'Brazil (+55)'), ('+52', 'Mexico (+52)'), ('+82', 'South Korea (+82)'), ('+65', 'Singapore (+65)'), ('+971', 'UAE (+971)')], default='+91', max_length=5)),
                ('mobile_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be 7-15 digits', regex='^\\d{7,15}$')])),
                ('resume', models.FileField(help_text='Upload your resume (PDF or Word format)', upload_to='resumes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
