# Generated by Django 5.2.6 on 2025-01-15 14:00

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_alter_userprofile_mobile_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('resume_summary', models.TextField(blank=True, null=True)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive Level')], default='entry', max_length=20)),
                ('total_experience', models.CharField(choices=[('0-1', '0-1 years'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5-10', '5-10 years'), ('10+', '10+ years')], default='0-1', max_length=10)),
                ('primary_skills', models.JSONField(blank=True, default=list, null=True)),
                ('secondary_skills', models.JSONField(blank=True, default=list, null=True)),
                ('domain_experience', models.JSONField(blank=True, default=dict, null=True)),
                ('education_details', models.JSONField(blank=True, default=list, null=True)),
                ('certifications', models.JSONField(blank=True, default=list, null=True)),
                ('projects', models.JSONField(blank=True, default=list, null=True)),
                ('strengths', models.JSONField(blank=True, default=list, null=True)),
                ('areas_for_improvement', models.JSONField(blank=True, default=list, null=True)),
                ('resume_score', models.IntegerField(default=0)),
                ('is_processing', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_message', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]