# Generated by Django 5.2.6 on 2025-09-23 18:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0004_candidateprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='is_processing',
            new_name='resume_processed',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='processing_message',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='resume_file',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='resume_text',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='total_experience',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='current_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='current_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='current_salary',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='desired_roles',
            field=models.JSONField(default=list, help_text='Desired job roles'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='notable_projects',
            field=models.JSONField(default=list, help_text='Key projects and achievements'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_locations',
            field=models.JSONField(default=list, help_text='Preferred work locations'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='soft_skills',
            field=models.JSONField(default=list, help_text='Communication, leadership, etc.'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='total_experience_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='total_experience_years',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='user_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr_app.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('manager', 'Manager'), ('admin', 'Admin')], default='candidate', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='areas_for_improvement',
            field=models.JSONField(default=list, help_text='Areas for development'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='certifications',
            field=models.JSONField(default=list, help_text='Professional certifications'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='domain_experience',
            field=models.JSONField(default=dict, help_text='Experience in different domains'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='education_details',
            field=models.JSONField(default=list, help_text='Education background'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='experience_level',
            field=models.CharField(choices=[('fresher', 'Fresher (0-1 years)'), ('junior', 'Junior (1-3 years)'), ('mid', 'Mid-level (3-5 years)'), ('senior', 'Senior (5-8 years)'), ('lead', 'Lead (8-12 years)'), ('principal', 'Principal (12+ years)')], default='fresher', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='primary_skills',
            field=models.JSONField(default=list, help_text='Primary technical skills'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='processing_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume_score',
            field=models.IntegerField(default=0, help_text='Resume quality score (0-100)'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume_summary',
            field=models.TextField(blank=True, default=1, help_text='AI-generated resume summary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='secondary_skills',
            field=models.JSONField(default=list, help_text='Secondary/supporting skills'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='strengths',
            field=models.JSONField(default=list, help_text='Identified strengths'),
        ),
    ]
