# Generated by Django 5.2.6 on 2025-09-24 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0005_rename_is_processing_candidateprofile_resume_processed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('provider', models.CharField(choices=[('udemy', 'Udemy'), ('coursera', 'Coursera'), ('linkedin', 'LinkedIn Learning'), ('pluralsight', 'Pluralsight'), ('internal', 'Internal Training')], default='udemy', max_length=20)),
                ('course_url', models.URLField()),
                ('skill_category', models.CharField(choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('fullstack', 'Full Stack Development'), ('mobile', 'Mobile Development'), ('devops', 'DevOps & Infrastructure'), ('data_science', 'Data Science & Analytics'), ('ai_ml', 'AI & Machine Learning'), ('cloud', 'Cloud Computing'), ('security', 'Cybersecurity'), ('project_management', 'Project Management'), ('soft_skills', 'Soft Skills & Leadership')], max_length=30)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('duration_hours', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('skills_covered', models.JSONField(default=list, help_text='List of specific skills covered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDevelopmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_gap_identified', models.CharField(max_length=100)),
                ('current_skill_level', models.CharField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('target_skill_level', models.CharField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('assignment_reason', models.TextField(help_text='AI-generated reason for recommendation')),
                ('priority_level', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('recommended', 'AI Recommended'), ('manager_assigned', 'Manager Assigned'), ('self_enrolled', 'Self Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='recommended', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('estimated_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('employee_feedback', models.TextField(blank=True)),
                ('manager_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courses', to=settings.AUTH_USER_MODEL)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_plans', to='hr_app.candidateprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.learningcourse')),
            ],
            options={
                'unique_together': {('employee_profile', 'course')},
            },
        ),
    ]
