# Generated by Django 5.2.6 on 2025-09-27 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0007_managerfeedback_feedbackcourserecommendation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillUpCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('instructor_name', models.CharField(max_length=100)),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('skills_covered', models.JSONField(default=list)),
                ('prerequisites', models.JSONField(default=list)),
                ('learning_objectives', models.JSONField(default=list)),
                ('course_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('assignment_type', models.CharField(choices=[('feedback_based', 'Feedback Based'), ('manual', 'Manual Assignment'), ('ai_recommended', 'AI Recommended')], default='manual', max_length=20)),
                ('has_video_assessment', models.BooleanField(default=False)),
                ('passing_score', models.IntegerField(default=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employeedevelopmentplan',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_development_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='assigned', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_skill_courses', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_app.managerfeedback')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hr_app.skillupcourse')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('employee', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules_completed', models.JSONField(default=list)),
                ('quiz_scores', models.JSONField(default=dict)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('login_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('average_session_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('improvement_areas', models.JSONField(default=list)),
                ('strengths_identified', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_progress', to='hr_app.courseassignment')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackActionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='action_assessments/videos/')),
                ('transcript', models.TextField()),
                ('ai_score', models.FloatField(default=0.0)),
                ('ai_feedback', models.TextField(blank=True)),
                ('questions_asked', models.JSONField(default=list)),
                ('answers', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cheating_detected', models.BooleanField(default=False)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='hr_app.feedbackaction')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('attention_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('engagement_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('facial_analysis_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_behavior_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('video_file_path', models.CharField(blank=True, max_length=500)),
                ('screenshots_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('technical_error', 'Technical Error')], default='scheduled', max_length=20)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_feedback', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_assessment', to='hr_app.courseassignment')),
            ],
        ),
        migrations.CreateModel(
            name='AttentionTrackingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('attention_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eye_contact_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('facial_expression', models.CharField(max_length=50)),
                ('head_position', models.CharField(max_length=50)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_data', to='hr_app.videoassessment')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
